{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.common }}
  {{- if and $val (ne $key "extraExistingKeys") (ne $key "extraVars") }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.secret.common.extraVars }}
  {{- range . }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $val := .Values.secret.api }}
  {{- if and $val (ne $key "extraExistingKeys") (ne $key "extraVars") }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.secret.api.extraVars }}
  {{- range . }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $val := .Values.secret.pdf }}
  {{- if and $val (ne $key "extraExistingKeys") (ne $key "extraVars") }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.secret.pdf.extraVars }}
  {{- range . }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
