apiVersion: v1
kind: Service
metadata:
  name: {{ (printf "%s-%s" (include "formio-enterprise-fullname" .) (.Values.api.name)) }}
  labels:
    {{- include "formio-enterprise-labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.api.name }}
  {{- if .Values.api.service.annotations }}
  annotations:
  {{ toYaml .Values.api.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.api.service.type "ClusterIP") .Values.api.service.clusterIP }}
  clusterIP: {{ .Values.api.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.api.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.api.service.loadBalancerClass }}
  {{- end }}
  {{- if .Values.api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.api.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.api.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.api.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.api.service.ipFamilies }}
  ipFamilies: {{ .Values.api.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  {{- if .Values.api.service.externalIPs }}
  externalIPs: {{ toYaml .Values.api.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.api.service.sessionAffinity }}
  sessionAffinity: {{ .Values.api.service.sessionAffinity }}
  {{- end }}
  {{- if eq .Values.api.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.api.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}
  {{- if (or (eq .Values.api.service.type "LoadBalancer") (eq .Values.api.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.api.service.externalTrafficPolicy | quote }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.api.service.publishNotReadyAddresses }}
  ports:
    - port: {{ .Values.api.service.port | default 80 }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "formio-enterprise-selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.api.name }}
---
{{- if .Values.pdf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ (printf "%s-%s" (include "formio-enterprise-fullname" .) (.Values.pdf.name)) }}
  labels:
    {{- include "formio-enterprise-labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.pdf.name }}
  {{- if .Values.pdf.service.annotations }}
  annotations:
  {{ toYaml .Values.pdf.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.pdf.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.pdf.service.type "ClusterIP") .Values.pdf.service.clusterIP }}
  clusterIP: {{ .Values.pdf.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.pdf.service.type "LoadBalancer") .Values.pdf.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.pdf.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.pdf.service.type "LoadBalancer") .Values.pdf.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.pdf.service.loadBalancerClass }}
  {{- end }}
  {{- if .Values.pdf.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.pdf.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.pdf.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.pdf.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.pdf.service.ipFamilies }}
  ipFamilies: {{ .Values.pdf.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  {{- if .Values.pdf.service.externalIPs }}
  externalIPs: {{ toYaml .Values.pdf.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.pdf.service.sessionAffinity }}
  sessionAffinity: {{ .Values.pdf.service.sessionAffinity }}
  {{- end }}
  {{- if eq .Values.pdf.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.pdf.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}
  {{- if (or (eq .Values.pdf.service.type "LoadBalancer") (eq .Values.pdf.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.pdf.service.externalTrafficPolicy | quote }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.pdf.service.publishNotReadyAddresses }}
  ports:
    - port: {{ .Values.pdf.service.port | default 80 }}
      targetPort: 4005
      protocol: TCP
      name: http
  selector:
    {{- include "formio-enterprise-selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.pdf.name }}
{{- end }}
