# Default values for deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appVersion:

replicaCount: 1

## App Vars
appEnv:
mongo:
licenseKey:
port:
<% if (package.server) { %>
portalEnabled:
portalSecret:
adminEmail:
adminPass:
dbSecret:
jwtSecret:
pdfServer:
baseUrl:
<% } %>

<% if (package.pdf && package.azure) { %>
## Azure Blob
formioAzureContainer:
formioAzureConnectionString:
<% } %>

<% if (package.pdf && package.aws) { %>
## AWS S3 Bucket
formioS3Key:
formioS3Secret:
formioS3Bucket:
formioS3Region:
textractOutputFolder:
textractRoleArn:
textractSnsTopicArn:
<% } %>

<% if (package.server) { %>
image:
  repository: 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
<% } %>
<% if (package.pdf) { %>
pdf:
  repository:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
<% } %>

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}