version: "3.8"
services:
  seaweedfs:
    image: chrislusf/seaweedfs
    restart: always
    ports:
      - "8333:8333"
      - "23646:23646"
    volumes:
      - "./data/seaweedfs/data:/data"
    environment:
      AWS_ACCESS_KEY_ID: CHANGEME
      AWS_SECRET_ACCESS_KEY: CHANGEME
    command: server -s3
  api-server:
    image: formio/formio-enterprise:latest
    mem_limit: 2048m
    restart: always
    links:
      - pdf-server
    ports:
      - "3000:3000"
      
    env_file:
      - .env
    volumes:
      - ./data:/data
  pdf-server:
    image: formio/pdf-server:latest
    restart: always
    mem_limit: 2048m
    links:
      - seaweedfs
    ports:
      - "4005:4005"
    env_file:
      - .env
    volumes:
      - ./data:/data
    
  nginx-proxy:
    image: nginx
    restart: always
    mem_limit: 128m
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d:ro"
    links:
      - api-server
      - pdf-server
